### ISSUE TITLE
Mistake in Tutorial #1

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS.data#109]
@davidkane9 A perceptive student found a typo in Tutorial #1: 

"Nice job! For now, I have set the scale on the y axis back to continuous. In our first diamonds boxplot, R automatically set labels on the tick marks at 0, 5000, 10000 and 15000. Try changing this so that we have labels at 0, 90000 and 18000. After this, add dollar signs to your labels. Note, this is different from and does not use labs()!" TYPO: It should be 9000, not 90000. Heads up for people who were initially confused like me.

**Comment by davidkane9** [comment]
Fixed!
