### ISSUE TITLE
Tutorial #1 Mistake

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS.data#110]
@davidkane9 The answer to this question in Tutorial 1:

"Great! Now, let's zoom in on our plot by setting  `xlim()` to the vector `c(500, 7000)`. Remember that `xlim()` should be placed inside of the `coord_` function, in this case, `coord_flip`."

is intended to be:

```
ggplot(data = diamonds, mapping=aes(x = cut, y = price)) +   
    geom_boxplot(outlier.alpha = 0) + 
    coord_flip(xlim = c(500,7000))
```

But, since we flipped the axes that looks like this: 

<img width="690" alt="Screen Shot 2020-09-06 at 1 50 43 PM" src="https://user-images.githubusercontent.com/4583367/92331935-0925b880-f048-11ea-9261-5e3abf330880.png">

I'm pretty sure you mean `ylim`: 

<img width="686" alt="Screen Shot 2020-09-06 at 1 50 53 PM" src="https://user-images.githubusercontent.com/4583367/92331931-ff03ba00-f047-11ea-868f-8d50479ae0d2.png">

**Comment by davidkane9** [comment]
fixed
