### ISSUE TITLE
Tutorial #1 Suggestion

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS.data#111]
For this hint:

```
In order to use two continouous variables in a `boxplot()`, 
use the `group = cut_` function, in this case, `group = cut_interval(..., n = ...)`. 
Remember that this function must be inside of `aes()`.
```

We should explain (1) that the first argument to `cut_interval` is the variable you want to cut, and (2) what "n" means in this context. 

smaller point: there's also a typo in continuous.

**Comment by davidkane9** [comment]
Fixed!
