### ISSUE TITLE
Tutorial #2: ifelse confusion

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS.data#121]
We briefly mention in the book that `ifelse()` and `if_else()` do the same thing but have different arguments. 

In Tutorial 2A, we include `ifelse()` as a hint but don't say very much about it in Characters: Exercise 20. In Tutorial 2B, we use `if_else()` exclusively and don't mention `ifelse()`. 

I've gotten a few questions about this, mainly from students using `ifelse()` but including the `condition, true, false` arguments from `if_else()` and being confused by the error.

I think we should:

1. Edit the hint in 2A Exercise 20 to clarify that the two functions are basically the same with the exception of the arguments and to see the book for more details. 
2. Mention this difference again in the hint to 2B Shaming 4, where we use `if_else()` for the first time.

**Comment by davidkane9** [comment]
Fixed
