### ISSUE TITLE
There are still spaces in the course_name

### ISSUE THREAD

**Issue by davidkane9** [davidkane9/PPBDS.data#68]
> library(PPBDS.data)
> qscores
# A tibble: 748 x 8
   course_name                                         department course_number term  enrollment hours rating instructor      
   <chr>                                               <chr>      <chr>         <chr>      <int> <dbl>  <dbl> <chr>           
 1 " Introduction to Black Poetry"                     AFRAMER    100Y          2019S         49   2.6    4.2 Jesse McCarthy  
 2 " American Democracy"                               AFRAMER    123Z          2019S         49   3.6    4.4 Cornel West     

Also, course_name should be "name"
course_number should be "number"
term should be formatted more nicely, like 2019-Spring, 2018-Fall or whatever

**Comment by tcweiss** [comment]
The problem has been solved. My apologies for not updating this sooner. I will be making more frequent pull requests from now on.

**Comment by davidkane9** [comment]
Looks good!
