### ISSUE TITLE
warnings in R CMD check 

### ISSUE THREAD

**Issue by davidkane9** [davidkane9/PPBDS.data#69]
See 

https://community.rstudio.com/t/how-to-solve-no-visible-binding-for-global-variable-note/28887

https://www.r-bloggers.com/no-visible-binding-for-global-variable/

**Comment by caievelyn** [comment]
Used fix from above, but now getting an error with '::' or ':::' imports not declared from:
    'learnr' 'learnrhash'. I think this has to do with how they're imported in DESCRIPTION (maybe requires: instead of imports:)?

**Comment by davidkane9** [comment]
No idea. I am an amateur when it comes to making R packages

**Comment by caievelyn** [comment]
Fixed in new pull request.
